version: '3'
services:
  client:
    build:
      context: ./client
    container_name: frontend-uploader
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./
    container_name: backend-uploader
    ports:
      - "5000:5000"
#     depends_on:
#       - mongodb

#   mongodb:
#     image: mongo
#     container_name: mongo-db
#     volumes:
#       - mongo-data:/data/db
#     ports:
#       - "27017:27017"

# volumes:
#   mongo-data:
